name: Consumer EC2 배포

on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle로 프로젝트 빌드
        run: ./gradlew clean build

      - name: SSH 프라이빗 키 저장
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: 빌드된 JAR 파일을 EC2로 복사
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no \
            build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app.jar

      - name: EC2에 SSH 접속해 서버 재시작
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              pkill -f 'java -jar' || true
              nohup java -jar /home/${USER}/app.jar > app.log 2>&1 &
          EOF
